runtime: python

# the PROJECT-DIRECTORY is the one with settings.py and wsgi.py
entrypoint: gunicorn -b :$PORT user_repo.wsgi # specific to a GUnicorn HTTP server deployment
env: flex # for Google Cloud Flexible App Engine

service: users

# any environment variables you want to pass to your application.
# accessible through os.environ['VARIABLE_NAME']
env_variables:
# the secret key used for the Django app (from PROJECT-DIRECTORY/settings.py)
  SECRET_KEY: 7wicu!$e-v!th%%tbz$$&v&w^w8rpwh@d&72p&u4dwa(@ama4r
  DEBUG: False # always False for deployment

# everything after /cloudsql/ can be found by entering >> gcloud sql instances describe DATABASE-NAME << in your Terminal
# the DATABASE-NAME is the name you gave your project's PostgreSQL database
# the second line from the describe output called connectionName can be copied and pasted after /cloudsql/
  DB_HOST: /cloudsql/kraft-users:us-central1-a:kraft-users
  DB_PORT:  5432 # PostgreSQL port
  DB_NAME: postgres
  DB_USER: postgres # either 'postgres' (default) or one you created on the PostgreSQL instance page
  DB_PASSWORD: Sahi@2010

#  STATIC_URL: 'https://storage.googleapis.com/BUCKET-NAME/static/' # this is the url that you sync static files to

handlers:
- url: /static_dev
  static_dir: static_dev


#handlers:
##- url: /static
##  static_dir: static_dev
#
#- url: /(.*\.css)
#  static_files: static/\1
#  upload: static/.*\.css

beta_settings:
# from command >> gcloud sql instances describe DATABASE-NAME <<
  cloud_sql_instances: kraft-users:us-central1-a:kraft-users

runtime_config:
  python_version: 3 # enter your Python version BASE ONLY here. Enter 2 for 2.7.9 or 3 for 3.6.4

#













#runtime: python
#env: flex
#entrypoint: gunicorn -b :$PORT user_repo.wsgi
#env_variables:
#    SECRET_KEY: '7wicu!$e-v!th%%tbz$$&v&w^w8rpwh@d&72p&u4dwa(@ama4r'
#    DEBUG: 'False'
#
#
#    DB_HOST: '/cloudsql/brain-sandbox:us-central1:customers'
#    DB_PORT: '5432' # PostgreSQL port
#    DB_NAME: 'kraft_user'
#    DB_USER: 'kraftuser' # either 'postgres' (default) or one you created on the PostgreSQL instance page
#    DB_PASSWORD: 'kraft@2010'
#
#    STATIC_URL: 'https://storage.googleapis.com/kraft_user_static/static_dev/'
#
#handlers:
#- url: /static_dev
#  static_dir: static_dev
#
#beta_settings:
#    cloud_sql_instances: brain-sandbox:us-central1:customers
#
#service: users
#
#runtime_config:
#  python_version: 3
